server:
  port: 6666

spring:
  application:
    name: gulimall-product
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xuxiaolei
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #主键自增
  mapper-locations: classpath:/mapper/**/*.xml #扫描.xml文件路径
